// Generated by scripts/generate-ascii-cat.mjs.
// Source: https://github.com/ts-animal/ts-animal/tree/main/src/zoo/cat-coffee
// License: MIT. Copyright (c) 2024 ts-animal.
export const personalCatAsciiFrames = [
  " ∧ _ ∧   \n(• ω •„) \n O☕ O )/",
  " ∧ _ ∧   \n(- ω -„) \n O☕ O )/",
  " ∧ _ ∧   \n(• ω •„) \n O☕ O )/",
  " ∧ _ ∧   \n(• ω •„) \n O☕ O )/",
  " ∧ _ ∧   \n(= ω =„) \n O☕ O )/",
  " ∧ _ ∧   \n(= ω =„) \n O☕ O )/",
  " ∧ _ ∧   \n(• ω •„) \n O☕ O )/",
  " ∧ _ ∧   \n(• ω •„) \n O☕ O )/"
] as const;

export const personalCatAsciiDelays = [180,180,180,420,180,420,180,420] as const;
